build:
    environment:
        php: '7.1.0'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS redirects"

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*
        - redirects/*